# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: header
  layoutpage: true
- name: footer
  layoutpage: true
- name: index
  unique: true
#  autogenerate: [article]
#  elements: [slider, info_boxes, recent_seminars, testemonials, contact]
#  controller: PagesController
#  Controller to use instead of the default Alchemy::PagesController
#  action: home
#  Controllers action to use instead of the default Alchemy::PagesController#show

- name: team
  elements: [article, team_member]
  autogenerate: [article]
- name: locations
  elements: [article, location]
  autogenerate: [article]
- name: standard
  elements: [article]
  autogenerate: [article]
#- name: contact
#  cache: false
#  unique: true
#  elements: [headline, contactform, text]
#  autogenerate: [headline, contactform]
- name: contact
  unique: true
  cache: false
  elements: [article, contactform]
  autogenerate: [article, contactform]
