# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: index
  unique: true
  elements: [article]
  autogenerate: [article]
#- name: home
#  unique: true
#  elements: [slider, info_box, recent_seminars, testemonials, contact]
##  autogenerate: []
#- name: team
#- name: locations
