menubar: false
toolbar:
  - undo redo | styleselect | bold italic removeformat | bullist numlist outdent indent | link | preview visualblocks visualchars
plugins:
  - lists
  - link
  - autolink
  - preview
  - paste
  - searchreplace
  - wordcount
  - visualblocks
  - visualchars
visualblocks_default_state: true
visualchars_default_state: true
height: 500
